guard 'sass',
  :input => 'sass',
  :output => 'css',
  :style => :compressed

guard :concat,
  type: "css",
  files: %w(master),
  input_dir: "css",
  output: "../static/style"

guard :concat,
  type: "js",
  files: %w(main),
  input_dir: "js",
  output: "../static/main.min"

guard 'uglify', :destination_file => "../static/main.min.js" do
  watch ('js/main.js')
end

guard 'livereload' do
  watch (%r{.+\.(sass|php|html|js|css)$})
end
